### ISSUE TITLE
[repo add] StarBreach

### ISSUE THREAD

**Issue by andreanespeca** [BSData/gallery#11]
would like to add my personal repository for StarBreach in the new gallery so to allow other user to download the data file directly from the app
https://github.com/andreanespeca/StarBreach
would be also great to have some sort of visual interface in the app to make the adding process easier.
Thanks

**Comment by amis92** [comment]
Hi. I'm not sure I'll be able to do the visual/tutorial thing, but:

Please make a PR to include your repository in registry. As an example, see https://github.com/BSData/gallery/blob/master/registry/entries/wh40k.catpkg.yml

You should add a `starbreach.catpkg.yml` in the same folder, with the following content:

```yml
location:
  github: andreanespeca/StarBreach
```

**Comment by amis92** [comment]
We're going to redirect old AppSpot endpoint onto this Gallery's, so when this happens, your StarBreach repo will be visible in the same list as currently users get when they open a new BattleScribe installation.

**Comment by amis92** [comment]
@andreanespeca - mention for additional attention 👆👆👆

**Comment by andreanespeca** [comment]
Will look into it as soon as possibile thanks for letting me know!

Il Ven 18 Set 2020, 18:17 Amadeusz Sadowski <notifications@github.com> ha
scritto:

**Comment by andreanespeca** [comment]
@amis92 i have created a pull request to include star breach in the gallery let me know if i have done anything wrong!
 THanks
